apiVersion: v1
kind: Secret
metadata:
  name: keycloak-sync-secret
type: Opaque
data:
  # The Keycloak base URL (e.g., http://keycloak.internal.svc)
  keycloak_url: aHR0cDovL3Nzby1mZXJpLWRldm9wcy1tYWNoaW5lLmRlcGxveS1hdC5teS5pZDo4MDgy
  
  # The Keycloak Realm name (e.g., master)
  keycloak_realm: bWFzdGVy
  
  # The Keycloak Client ID for the sync service (e.g., grafana-sync-client)
  keycloak_client_id: c3luYy1ncm91cHMtcHJvZ3JhbQ==
  
  # The Keycloak Client Secret (the most sensitive value)
  keycloak_client_secret: bE9OcGh1ZDFSVU1GZDYydEo5d0tGM2Nvb2pWQXZ6amo=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-sync-secret
type: Opaque
data:
  # The Grafana base URL (e.g., http://grafana.internal.svc)
  grafana_url: aHR0cDovL21vbml0b3JpbmctZmVyaS1kZXZvcHMtbWFjaGluZS5kZXBsb3ktYXQubXkuaWQ6ODA4MQ==
  
  # The Grafana Service Account Token (the highly sensitive API key)
  grafana_token: Z2xzYV8wZFR2bnVMNGF2VTJ1dHZmU2lub0REWW1ESUhETHE3Ml8xNWJmNTNlNQ==
  
  # --- OPTIONAL: If using Basic Auth lookup ---
  grafana_user: YWRtaW4=
  grafana_pass: cHJvbS1vcGVyYXRvcg==